# Generated by Django 5.1.3 on 2024-12-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('product', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Product')),
                ('price', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField()),
                ('revenue', models.PositiveIntegerField()),
            ],
        ),
    ]
