# Generated by Django 5.1.3 on 2024-12-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventSalesSystem', '0003_rename_image_affiliate_preview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('product', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Product')),
                ('price', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField()),
                ('revenue', models.PositiveIntegerField()),
            ],
        ),
    ]
