# Generated by Django 5.1.3 on 2024-12-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventSalesSystem', '0004_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_posted', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('work_schedule', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('requirements', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('payment_verification', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('budget', models.CharField(blank='', default='', max_length=200, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('proposal', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
