# Generated by Django 5.1.3 on 2024-12-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventSalesSystem', '0005_remotework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotework',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remotework',
            name='requirements',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
