# Generated by Django 5.1.3 on 2024-12-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventSalesSystem', '0006_alter_remotework_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotework',
            name='requirements',
        ),
        migrations.AddField(
            model_name='remotework',
            name='requirements1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remotework',
            name='requirements2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remotework',
            name='requirements3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remotework',
            name='requirements4',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remotework',
            name='requirements5',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
