# Generated by Django 5.1.3 on 2024-12-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventSalesSystem', '0008_alter_remotework_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('course_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
