# Generated by Django 5.1.3 on 2024-12-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0003_remove_location_address_remove_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
