# Generated by Django 5.1.3 on 2024-12-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0004_eventdetail_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
