# Generated by Django 5.1.3 on 2024-12-06 13:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0005_event_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0))),
                ('event_detail', models.TextField(blank=True, default='', null=True)),
                ('location', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='EventManager.location')),
            ],
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0))),
                ('event_detail', models.TextField(blank=True, default='', null=True)),
                ('location', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='EventManager.location')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0))),
                ('event_detail', models.TextField(blank=True, default='', null=True)),
                ('location', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='EventManager.location')),
            ],
        ),
    ]
