# Generated by Django 5.1.3 on 2024-11-27 08:27

import EventManager.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0005_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name=EventManager.models.Event)),
                ('key_details', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('description', models.TextField()),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManager.event')),
            ],
        ),
    ]
