# Generated by Django 5.1.3 on 2024-11-27 08:44

import EventManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0006_eventdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='description',
            field=models.TextField(verbose_name=EventManager.models.Event),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='location',
            field=models.CharField(max_length=100, verbose_name=EventManager.models.Event),
        ),
    ]
