# Generated by Django 5.1.3 on 2024-12-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0006_kid_lifestyle_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kid',
            old_name='description',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='kid',
            old_name='end_date',
            new_name='end_date1',
        ),
        migrations.RenameField(
            model_name='kid',
            old_name='event_detail',
            new_name='event_detail1',
        ),
        migrations.RenameField(
            model_name='kid',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='kid',
            old_name='location',
            new_name='location1',
        ),
        migrations.RenameField(
            model_name='kid',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='kid',
            old_name='qr_code',
            new_name='qr_code1',
        ),
        migrations.RenameField(
            model_name='kid',
            old_name='start_date',
            new_name='start_date1',
        ),
    ]
