# Generated by Django 5.1.3 on 2024-12-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0007_rename_description_kid_description1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifestyle',
            old_name='description',
            new_name='description2',
        ),
        migrations.RenameField(
            model_name='lifestyle',
            old_name='end_date',
            new_name='end_date2',
        ),
        migrations.RenameField(
            model_name='lifestyle',
            old_name='event_detail',
            new_name='event_detail2',
        ),
        migrations.RenameField(
            model_name='lifestyle',
            old_name='image',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='lifestyle',
            old_name='location',
            new_name='location2',
        ),
        migrations.RenameField(
            model_name='lifestyle',
            old_name='name',
            new_name='name2',
        ),
        migrations.RenameField(
            model_name='lifestyle',
            old_name='qr_code',
            new_name='qr_code2',
        ),
        migrations.RenameField(
            model_name='lifestyle',
            old_name='start_date',
            new_name='start_date2',
        ),
    ]
