# Generated by Django 5.1.3 on 2024-12-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0008_rename_description_lifestyle_description2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='description3',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='end_date',
            new_name='end_date3',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='event_detail',
            new_name='event_detail3',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='location',
            new_name='location3',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='name3',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='qr_code',
            new_name='qr_code3',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='start_date',
            new_name='start_date3',
        ),
    ]
