# Generated by Django 5.1.3 on 2024-11-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0009_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
