# Generated by Django 5.1.3 on 2024-11-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0010_event_event_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
