# Generated by Django 5.1.3 on 2024-12-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0012_remove_display_description_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
