# Generated by Django 5.1.3 on 2024-12-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0013_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
