# Generated by Django 5.1.3 on 2024-12-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0017_location_remove_event_date_alter_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='date',
        ),
    ]
