# Generated by Django 5.1.3 on 2024-12-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0018_remove_display_date'),
    ]

    operations = [
    ]
