# Generated by Django 5.1.3 on 2024-12-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0019_auto_20241203_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
